### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cortopy**
Add instructions for VSCode

### CODE REVIEW

**Comment by cortopy** [comment]
I'm not too sure if this is the right README though. I just followed the suggestion in https://github.com/pyoner/svelte-typescript/issues/9 but maybe users may find it more easily if it's in the preprocessor's RADME

**Comment by pyoner** [comment]
Thank you for the PR!

What do you think of adding `svelte.config.js` to the template?
I have many questions in the telegram chat about this problem and many people use VsCode.
I think that addition `svelte.config.js` to the template will solve this problem and people will be happy :)

**Comment by cortopy** [comment]
> Thank you for the PR!
> 
> What do you think of adding `svelte.config.js` to the template?
> I have many questions in the telegram chat about this problem and many people use VsCode.
> I think that addition `svelte.config.js` to the template will solve this problem and people will be happy :)

I thought about that too. A lot of people use VSCode these days, but what about those that don't? They'd get a file they don't need

It's a tricky one

**Comment by sw-yx** [comment]
a readme is fine tho imo

**Comment by pyoner** [comment]
@cortopy @sw-yx ok
thanks for the thought!

**Pull request merged**
